version: 3

dotenv:
  - .env

tasks:
  dev:
    env:
      NODE_ENV: development
    cmds:
      - npm run dev

  run:
    env:
      NODE_ENV: production
    cmds:
      - npm run start

  docker:build:
    cmds:
      - docker build -t wo-api:latest .

  docker:stop:
    cmds:
      - docker stop wo-api 2>/dev/null || true
      - docker rm wo-api 2>/dev/null || true

  docker:run:
    deps:
      - docker:stop
    cmds:
      - docker run --rm -p 3000:3000 --name wo-api wo-api:latest
